# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

# Use Python >=3.13 to match pyproject.toml requirement
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Upgrade pip
RUN pip install --no-cache-dir --upgrade pip

# Copy project metadata
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN pip install --no-cache-dir .

# Copy application source
COPY main.py ./

# Ensure unbuffered output for logs
ENV PYTHONUNBUFFERED=1

# Default command to run the MCP server
CMD ["python", "main.py"]
